return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "clangd",
      "css-lsp",
      "deno",
      "emmet-language-server",
      "eslint-lsp",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "markdownlint",
      "marksman",
      "prettier",
      "pyright",
      "rubocop",
      "ruby-lsp",
      "rubyfmt",
      "shellcheck",
      "shfmt",
      "solargraph",
      "stimulus-language-server",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
